version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:19.0.2
    steps:
      - checkout

      - run:
          name: Test de l'application
          command: mvn test

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/site/jacoco

workflows:
  IntegrationContinue:
    jobs:
      - test
