name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies and Test
        uses: actions/setup-java@v2
        with:
          java-version: '11'
        env:
          GITHUB_KEY: ${{ secrets.GITHUB_KEY }}
        run: |
          git clone https://$GITHUB_KEY@github.com/SAE-DACS-S4/CryptageVote.git;
          cd CryptageVote;
          mvn clean install;
          cd ..
